### ISSUE TITLE
Problema nell'invio della mail di autenticazione

### ISSUE THREAD

**Issue by JeyDi** [PythonGroupBiella/SitoPGB#1]
Quando mando la mail con la richiesta di autenticazione non mi arriva sulla mia casella di posta e quindi non posso entrare nella sezione dell'utente.

**Comment by JeyDi** [comment]
Il problema si presenta al primo invio con chrome della mail, se premo su invia un'altra mail me la rimanda.

**Comment by Burlesco70** [comment]
In dev ho configurato come mail server mailtrap e le mail hanno sempre funzionato.
Vedremo quando sarà deployato.
Per ora non chiudo la issue.
