### ISSUE TITLE
Problema nella navigazione mentre sono in attesa dell'autenticazione

### ISSUE THREAD

**Issue by JeyDi** [PythonGroupBiella/SitoPGB#2]
Dopo aver richiesto l'accesso (ovvero dopo aver effettuato la registrazione) e mentre sono in attesa della mail non riesco a raggiungere le altre pagine del portale pubbliche che prima potevo visualizzare.
Backend restituisce: /auth/unconfirmed con HTTP 200.

![image](https://user-images.githubusercontent.com/8246117/100937856-fd854900-34f3-11eb-9164-738796419859.png)

**Comment by Burlesco70** [comment]
Sì, c'era una redirect voluta, se l'utente non è confermato, che viene eseguita prima di ogni request se l'utente è autenticato:
@auth_blueprint.before_app_request

Normalmente, credo, un utente registrato conferma l'email o non si logga nemmeno.
Comunque ho fatto una modfica in modo che l'utente non confermato possa navigare nelle tre funzionalità ad accesso libero
